name: Publish Staging Enviorment

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      output: ${{ steps.filter.outputs.package }}
    
    steps:
    - uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          package:
            - 'main.js'

    - name: change package
      if: steps.filter.outputs.package == 'true'
      run: echo "package change"

    - name: Didn't change package
      if: steps.filter.outputs.package != 'true'
      run: echo "Package didn't change"