
name: Publish Staging Enviorment

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      output: ${{ steps.filter.outputs.package }}
    
    steps:
    - uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          package:
            - 'actions/package.json'

  publish:
    runs-on: ubuntu-latest
    needs: check

    env:
      TEST_STRING: ${{ secrets.TEST_STRING }} 
      TEST_URL: ${{ secrets.TEST_URL }}

    if: needs.check.outputs.output != 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: actions/package-lock.json

      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Make env file
        working-directory: ./actions
        run: |
          cd env
          touch .env
          echo API_TEST="$TEST_STRING" >> .env
          echo API_MORE="$TEST_URL" >> .env
          cat .env

      - name: Install Dependencies
        working-directory: ./actions
        run: npm install

      - name: Publish App
        working-directory: ./actions
        run: expo publish --release-channel preview

  build:
    runs-on: macos-latest
    needs: check

    if: needs.check.outputs.output == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: actions/package-lock.json

      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Dependencies
        working-directory: ./actions
        run: npm install

      - name: Install Pod
        working-directory: ./actions
        run: |
          cd ios
          pod install

      - name: Build App
        working-directory: ./actions
        run: eas build --profile preview --platform android --non-interactive