name: Publish Staging Enviorment

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      output: ${{ steps.filter.outputs.package }}
    
    steps:
    - uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          package:
            - 'main.js'

  publish:
    runs-on: ubuntu-latest

    needs: check

    if: needs.check.outputs.output != true

    steps:
      - name: check publish
        run: |
          echo '${{needs.check.outputs.output}}'
          echo '${{needs.path-filter.outputs.output}}'
          echo '${{needs}}'

  build:
    runs-on: ubuntu-latest

    needs: check

    if: needs.check.outputs.output == true

    steps:
      - name: check build
        run: echo "build"