name: Publish Staging Enviorment

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - name: Running test
        run: |
          echo test this
          ls -a