
name: Publish Staging Enviorment

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      output: ${{ steps.filter.outputs.package }}
    
    steps:
    - uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          package:
            - 'actions/package.json'

  publish:
    runs-on: ubuntu-latest
    needs: check

    if: needs.check.outputs.output != 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: actions/package-lock.json

      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: test output
        run: |
          echo "working"

  build:
    runs-on: ubuntu-latest
    needs: check

    if: needs.check.outputs.output == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1

      - name: check build
        run: echo "build"