name: Publish Staging Enviorment

on:
  push:
    branches: [main]

jobs:
  publish:
    - name: Get changed.
        uses: jitterbit/get-changed-files@v1
        id: files-changed
        with: 
          format: space-delimited

    if: contains(steps.files-changed.outputs.all, 'main.js') == 'false'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
          
      - name: Check publish
        run: |
          echo "Publish run"

  build:
    - name: Get changed.
        uses: jitterbit/get-changed-files@v1
        id: files-changed
        with: 
          format: space-delimited

    if: contains(steps.files-changed.outputs.all, 'main.js') == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1

      - name: Check build
        run: |
          echo "Build run"