name: Publish Staging Enviorment

on:
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      output: ${{ steps.filter.outputs.package }}
    
    steps:
    - uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          package:
            - 'main.js'

  publish:
    runs-on: ubuntu-latest
    needs: check

    if: needs.check.outputs.output != 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm

      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: checking expo
        run: expo

      - name: expo version
        run: |
          echo "testing if there is an error"

  build:
    runs-on: ubuntu-latest
    needs: check

    if: needs.check.outputs.output == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1

      - name: check build
        run: echo "build"